### ISSUE TITLE
Support for multiple return values in NDX-DN11

### ISSUE THREAD

**Issue by roman-khimov** [ngdenterprise/design-notes#4]
NDX-DN11 needs to be updated to support multiple return values from functions (see neo-project/neo-debugger#17).

As an obvious suggestion we can change Method's `return-type` to `return-values` with the same type as `parameters`.

**Comment by AnnaShaleva** [comment]
Just to stay in touch, is there any update on this issue?

As it was said in the https://github.com/neo-project/neo-debugger/issues/17#issuecomment-612992671, while it's prohibited to use multiple return values in the exported contract methods, we still have `CALL` and `CALL_L` instructions that doesn't check the unloaded context stack and allow to have multiple return values (not a single array of multiple values). Technically, in neo-go we can write, compile, deploy and successfully invoke the following code:
```
package main

// Main is a single exported contract method that returns the sum of 1 and 2.
func Main() int {
	var a, b int
	a, b = f()
	return a + b
}

func f() (int, int) {
	return 1, 2
}
```
And the resulting byte-code doesn't contain `f`'s return values packing:
```
NEO-GO-VM 0 > ops
INDEX    OPCODE      PARAMETER
0        INITSLOT    2 local, 0 arg    <<
3        PUSH0       
4        STLOC0      
5        PUSH0       
6        STLOC1      
7        CALL        15 (8/08)
9        STLOC0      
10       STLOC1      
11       LDLOC0      
12       LDLOC1      
13       ADD         
14       RET         
15       PUSH2       
16       PUSH1       
17       RET
```
It would be nice to be able to debug this code using DN11 debug info specification.

@devhawk, sorry to bother you, but IIUC, multiple return values are currently not supported in the neo-devpack? i saw the https://github.com/neo-project/neo-devpack-dotnet/pull/238, but it seems that it uses array for this.

**Comment by devhawk** [comment]
It's no bother @AnnaShaleva (and sorry for my delayed response). 

I've been working on a significant upgrade to the debug format in order to better support inspection of contract data. You can read an [overview here](https://github.com/neo-project/neo-debugger/blob/master/docs/storage-schema-overview.md) and there is a [draft PR](https://github.com/neo-project/proposals/pull/151) in the neo proposals repo describing the updated format.

The V2 debug info has a [construct for encoding Struct type info](https://github.com/devhawk/proposals/blob/devhawk/ssp/nep-19.mediawiki#struct). We could do something similar for methods that return multiple values like this. 

Note, since debug info is an official NEP now, I opened https://github.com/neo-project/proposals/issues/157 to track this issue and am closing this one down.
